### ISSUE TITLE
Ubuntu 16.04: can not build image with working DHCP

### ISSUE THREAD

**Issue by dannyman** [grnet/snf-image#90]
My first challenge is that the interface name is ... not eth0.  When cooking an image I fix that thus:

> To make interface name static to "eth0" did edit /etc/default/grub and set:
> 
> GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=0 biosdevname=0"
> 
> sudo update-grub

My next challenge is that Ubuntu 16.04 is not doing dhcp. Here is our manual fix for that:

> To get networking to actually work, did edit /etc/network/interfaces and set:
> 
> auto eth0
> allow-hotplug eth0
> iface eth0 inet dhcp

When I then cook a working image with snf-mkimage, and launch a test instance, the last line that makes DHCP work is gone. (`iface eth0 inet dhcp`)

I looks like this line should be getting set after all in snf-image-helper/networking/ifupdown.sh.in ?

This looks sketchy ... snf-image is installed, but can not install snf-image-helper because NTFS/UFS (neither of which we care here) and then even though aptitude says we have 0.19.1-1 snf-mkimage itself says 0.10 ...

```
0-15:01 djh@ganeti06-23 ~$ sudo aptitude show snf-image
Package: snf-image                       
State: installed
Automatically installed: no
Version: 0.19.1-1~trusty
Priority: extra
Section: admin
Maintainer: Nikos Skalkotos <skalkoto@grnet.gr>
Architecture: all
Uncompressed Size: 207 k
Depends: debconf (>= 0.5) | debconf-2.0, kpartx, curl, mbr, python,
         python-prctl, python-scapy
Conflicts: snf-image-host, snf-image-host
Breaks: snf-image-host (< 0.8), snf-image-host (< 0.8)
Replaces: snf-image-host, snf-image-host
Enhances: ganeti
Description: Image Based Ganeti OS Provider
 Ganeti is a cluster virtual server management software tool built on top of
 existing virtualization technologies such as Xen or KVM and other Open Source
 software. Once installed, the tool will take over the management part of the
 virtual instances. 

 This package provides an OS Provider for Ganeti, that allows the installation
 of predefined or custom Images. It is the main provider of the Synnefo Cloud
 Management Software.
Homepage: https://code.grnet.gr/projects/snf-image

0-15:01 djh@ganeti06-23 ~$ sudo apt-get install snf-image-helper
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 snf-image-helper : Depends: ntfsprogs but it is not installable
                    Depends: ufsutils but it is not installable
E: Unable to correct problems, you have held broken packages.
```

130-15:03 djh@ganeti06-23 ~$ sudo snf-mkimage --version
0.10

**Comment by dannyman** [comment]
Workaround: launch instance with `-O img_properties='{"EXCLUDE_TASK_ConfigureNetwork":"yes"}'`

**Comment by skalkoto** [comment]
Hello Daniel,

You are confusing 2 different projects: `snf-image-creator` and `snf-image`. `snf-mkimage` is part of `snf-image-creator` which is the project for creating images and it's current version is 0.10.1. On the other hand `snf-image-helper` is a package that is internally used by `snf-image` (current version: 0.20), to construct the helper image you download at the post-install phase. You are not supposed to install `snf-image-helper` on any system. Actually many users run on this and we are planning to find a way to hide it.

Regarding the dhcp thing, the ConfigureNetwork task of snf-image will create the Networking configuration according to the information Ganeti will expose. The problem is that when you add a VM to a network, snf-image is not able to tell if it should create a static configuration or a use dhcp. So, by default it will use a static configuration unless some info is missing (for example if ganeti provides an IP but not a subnet) or if the network has a tag that is inside a predefined set of dhcp tags. By default the dhcp tags: `auto`, `dhcp`, `nfdhcpd`, but you are free to override this list by overriding the value of `DHCP_TAGS` option in `/etc/default/snf-image`:

```
# DHCP_TAGS: Space separated list of Ganeti network tags. snf-image will
# configure a VM's NIC to use DHCP if the card is expected to have an IPv4
# address and any of those tags is present in the card's NETWORK_TAGS variable.
# DHCP_TAGS="auto dhcp nfdhcpd"

# STATEFUL_DHCPV6_TAGS: Space separated list of Ganeti network tags. snf-image
# will configure a VM's NIC to use DHCPv6 if the card is expected to have an
# IPv6 address and any of those tags is present in the card's NETWORK_TAGS
# variable.
# STATEFUL_DHCPV6_TAGS="dhcpv6 stateful_dhcpv6"

# STATELESS_DHCPV6_TAGS: Space separated list of Ganeti network tags. snf-image
# will configure a VM's NIC to perform SLAAC and Stateless DHCPv6 if the card
# is expected to have an IPv6 address and any of those tags is present in the
# card's NETWORK_TAGS variable.
# STATELESS_DHCPV6_TAGS="nfdhcpd stateless_dhcpv6"
```

What's the exact ganeti command you use to create the Ubuntu VM?

P.S: I've solved the eth0 naming thing the same way as you.

**Comment by dannyman** [comment]
We have ended up doing like so:

`sudo gnt-instance add -s 12G -B memory=2G,vcpus=1 -o snf-image+default -O img_format=diskdump,img_id=ubuntu1604,img_properties='{"EXCLUDE_TASK_ConfigureNetwork":"yes"}' --no-name-check --no-ip-check fully.qualified.host.name`

Thank you for the pointer to `/etc/default/snf-image` that looks like a handy resource in general. I'll try setting `DHCP_TAGS="dhcp"`

**Comment by dannyman** [comment]
Setting `DHCP_TAGS="dhcp"` in `/etc/default/snf-image` has no effect. The documentation referring to `NETWORK_TAGS` is all the more confusing. How do I tell SNF to configure eth0 as DHCP? I tried parsing the scripts, &c but could not figure it out.

Anyway, as I indicated above, passing `img_properties='{"EXCLUDE_TASK_ConfigureNetwork":"yes"}'` gets the job done for us.

**Comment by skalkoto** [comment]
Well, typically you have some networks defined in your ganeti cluster:
```
# gnt-network list
Network Subnet           Gateway       MacPrefix GroupList                Tags
nat     192.168.100.0/28 192.168.100.1 -         default (bridged, br100) nfdhcpd
test6   192.0.2.0/29     -             -         default (routed, test6)  ip-less-routed,nfdhcpd
```
In the example above there is an IPv4 network: `nat` and one which also has IPv6 info associated with is: `test6`.
```
# gnt-network info test6
Network name: test6
UUID: 46213c2b-f81e-455d-b190-0fcb5721e996
Serial number: 2
  Subnet: 192.0.2.0/29
  Gateway: None
  IPv6 Subnet: 2001:618:2ffc:1201::/64
  IPv6 Gateway: 2001:618:2ffc:1201::1
  Mac Prefix: None
  Size: 8
  Free: 6 (75.00%)
  Usage map:
       0 X......X                                                         63
         (X) used    (.) free
  externally reserved IPs:
    192.0.2.0, 192.0.2.7
  connected to node groups:
    default (routed on test6)
  used by 3 instances:
    debian1: 0:None
    debian2: 0:None
    debian_666: 1:None
```
I think you cannot have a network with no "Subnet" even if you only want to use it as IPv6 only.

When you create an instance, you attach it to some network like this:
```
gnt-instance add -o snf-image+default -t plain --no-name-check --no-ip-check \
--os-parameters img_passwd=****,img_format=diskdump,img_id=debian.diskdump \
--disk 0:size=5G -B memory=2G \
--net 0:network=nat,ip=pool --net 1:network=test6 \
debian
```

This command will add 2 NICs to the instance. The first will be attached to network `nat` and the second to: `test6`. This will make ganeti expose the following environment variables to the `snf-image`
```
NIC_0_BRIDGE="br100"
NIC_0_FRONTEND_TYPE="paravirtual"
NIC_0_IP="192.168.100.4"
NIC_0_LINK="br100"
NIC_0_MAC="aa:00:00:49:09:1d"
NIC_0_MODE="bridged"
NIC_0_NETWORK_GATEWAY="192.168.100.1"
NIC_0_NETWORK_NAME="nat"
NIC_0_NETWORK_SUBNET="192.168.100.0/28"
NIC_0_NETWORK_TAGS="nfdhcpd"
NIC_0_NETWORK_UUID="761e3cfe-f329-4a48-ba4f-05ec6b3a15ad"
NIC_0_UUID="b2d345c9-e819-44c7-bee4-b6940fb3ac1d"
NIC_1_FRONTEND_TYPE="paravirtual"
NIC_1_LINK="test6"
NIC_1_MAC="aa:00:00:fa:cd:eb"
NIC_1_MODE="routed"
NIC_1_NETWORK_GATEWAY6="2001:618:2ffc:1201::1"
NIC_1_NETWORK_NAME="test6"
NIC_1_NETWORK_SUBNET="192.0.2.0/29"
NIC_1_NETWORK_SUBNET6="2001:618:2ffc:1201::/64"
NIC_1_NETWORK_TAGS="nfdhcpd ip-less-routed"
NIC_1_NETWORK_UUID="46213c2b-f81e-455d-b190-0fcb5721e996"
NIC_1_UUID="9d9c8f2f-d0bd-451e-afc1-ee3ae679d3a7"
NIC_COUNT="2"
```
Based on those information the `ConfigureNetwork` configuration task of `snf-image` will create the instance's `/etc/network/interfaces`. From the provided information `snf-image` will realize that the first card is attached to an IPv4 network (`NIC_0_NETWORK_SUBNET6` is missing) and that the second card is attached to a IPv6 only network(`NIC_1_IP` is missing). The problem here is that we have an IP and a SUBNET for NIC_0 and we cannot tell weather the user wants to create a static configuration for this NIC or to perform DHCP. This is were the network tags come into the picture. If all needed information are present, snf-image will do a static configuration for the NIC unless there is a network tag that indicates otherwise. The same problem exists with IPv6. We cannot somehow tell whether the card should be configured to perform a stateful or stateless DHCPv6 (as far as I know static IPv6 configuration is not supported in Ganeti).

What I hadn't realized was that if you don't explicitly define a network card (your case), Ganeti will still create one with no further info associated with it:
```
NIC_0_BRIDGE="br100"
NIC_0_FRONTEND_TYPE="paravirtual"
NIC_0_LINK="br100"
NIC_0_MAC="aa:00:00:e6:9c:1a"
NIC_0_MODE="bridged"
NIC_0_UUID="9145aa67-4355-4349-9adc-2c4621f91276"
NIC_COUNT="1"
```

From `snf-image`'s point of view this card is not attached to any network, hence it will just clear `/etc/network/interfaces`. I'll change this in the next version of snf-image to allow the user to decide what to do it circumstances like this one. Performing dhcp is a reasonable fall back behavior.

**Comment by dannyman** [comment]
Thank you for the science on `gnt-network` ... we haven't needed it thus far but in addition to fixing DHCP, this appears to answer a question I had elsewhere about getting snf-image to set up images with static addresses, which would be a big win for us.

I agree that having DHCP as a reasonable fallback will be nice in a future release.
