### ISSUE TITLE
Inconsistencies regarding helper images

### ISSUE THREAD

**Issue by kasimon** [grnet/snf-image#91]
Hi,

while trying to mirror the snf helper images, I noticed two inconsistencies:

First: `snf_image_helper_image-0.20.1.tar.xz.md5sum` contains a path, breaking automatic download verification:

```
# wget -q -O- https://cdn.synnefo.org/snf_image_helper_image-0.20.1.tar.xz.md5sum
513140d681c40ce009af8f1098268b90  /tmp/snf_image_helper_image-0.20.1-1-jessie.tar.xz

# md5sum --check --quiet snf_image_helper_image-*.md5sum
md5sum: /tmp/snf_image_helper_image-0.20.1-1-jessie.tar.xz: No such file or directory
/tmp/snf_image_helper_image-0.20.1-1-jessie.tar.xz: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
md5sum: snf_image_helper_image-0.20-1~jessie.tar.xz: No such file or directory
snf_image_helper_image-0.20-1~jessie.tar.xz: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
```

Second: My mirror script assumes that for every package in the Packages file, there exists an image with the same version number. If this is the case, the image for `0.19~rc2` is missing:

```
# ./update-snf-image-helper 
https://cdn.synnefo.org/snf_image_helper_image-0.19~rc2.tar.xz:
2016-10-12 20:31:06 ERROR 404: Not Found.
```

Best,
Karsten

**Comment by kasimon** [comment]
Btw, this is the current version of my mirroring script, in case something is wrong with it:
```
#!/bin/bash

# This script will mirror all snf helper images to a local directory.

set -e
set -u

DIST="jessie"   # "stable" doesn't work
PACKAGES="http://apt.dev.grnet.gr/$DIST/Packages"
URLBASE="https://cdn.synnefo.org"

get_snf-image_versions () {
  curl -s "$PACKAGES" | grep "Filename: $DIST/snf-image_" | cut -d_ -f2 | cut -d- -f1  #| grep -v "0.19~rc2"
}

get_snf-image_versions | while read HELPER_VERSION ; do
  IMG="snf_image_helper_image-$HELPER_VERSION.tar.xz"
  IMGMD5="$IMG.md5sum"
  wget -kc -nv $URLBASE/$IMG -O $IMG || continue
  wget -kc -nv $URLBASE/$IMGMD5 -O $IMGMD5
done

md5sum --check --quiet snf_image_*.md5sum
```

**Comment by skalkoto** [comment]
This thing with the md5sum file is that cdn.synnefo.org just redirects to the actual location of the image file, which is our storage service: pithos. 
So, `snf_image_helper_image-0.20.1.tar.xz` is actually located here: https://pithos.okeanos.grnet.gr/public/M3pq4cGSWKgCczC6oz2sl5 and 
 `snf_image_helper_image-0.20.1.tar.xz.md5sum` is located here: https://pithos.okeanos.grnet.gr/public/bcBtAGt9sBtVY49HYCbT62

And the file name of the actual files is not the one you see in cdn.synnefo.org. If you download the link from the browser, where the Content-Disposition field of the header is respected, you will realize that the actual filename of the pithos file is: `snf_image_helper_image-0.20.1-1-jessie.tar.xz` and for versions prior to 0.19, the file looked like this: `snf_image_helper_image-0.18.1-1~wheezy.tar.xz`. This has to do with the fact that the image hosts a debian package of snf-image-helper with version `0.20.1-1~jessie`. But this helper image is used by any deployment of snf-image v0.20. This one for wheezy, the one for jessie, the one for Ubuntu or even the one that is installed from source. So, the `snf-image-update-helper` script should not depend on the package version (1~jessie), only on the software version (0.20.1). This is why the cdn.synnefo.org one has stripped the package version. On the other hand, it's still better to have the whole package version in the actual filename, because if a packaging bug occurs in a version then we might need to create a new helper image and having it with the same name is not a good thing to do.

The thing you face with the md5sum is that prior to version 0.20.1 the md5sum contained the cdn.synnefo.org name inside, but this seemed to be wrong, because this was not the actual file name and it depends on how you download it. wget and curl both have an option for supporting "Content-Dispostition" headers, but both are buggy. . So, we've changed it and added code to `snf-image-update-helper` to handle this change: https://github.com/grnet/snf-image/blob/develop/snf-image-host/snf-image-update-helper.in#L140-L148

We are thinking of adding the links to a page to allow easy mirroring. We haven't decided yet how we are going to do this.

For now, your script is great, something like this could make you overcome your problem:
```
for sum in *.md5sum; do
    name=$(basename "$sum" .md5sum)
    sed -i 's/ .\+$/'" $name"'/' "$sum"
done
```
Careful, there are 2 spaces between s/ and .\+ and /"" and $name

**Comment by kasimon** [comment]
Okay, understood. I applied your fix to the script, and now everything works, apart from https://cdn.synnefo.org/snf_image_helper_image-0.19~rc2.tar.xz still missing, I'll add an explicit filter for this one. Will this be fixed or should I wait until it ages out of the package repository?

For the record, here is the (at least for me) complete working script:
```
#!/bin/bash

# This script will mirror all snf helper images to a local directory.

set -e
set -u

DIST="jessie"   # "stable" doesn't work
PACKAGES="http://apt.dev.grnet.gr/$DIST/Packages"
URLBASE="https://cdn.synnefo.org"

get_snf-image_versions () {
  curl -s "$PACKAGES" | grep "Filename: $DIST/snf-image_" | cut -d_ -f2 | cut -d- -f1 | grep -v "0.19~rc2" | sort -u
}

get_snf-image_versions | while read HELPER_VERSION ; do
  IMG="snf_image_helper_image-$HELPER_VERSION.tar.xz"
  IMGMD5="$IMG.md5sum"
  [ -a $IMG ] || wget -kc -nv $URLBASE/$IMG -O $IMG || continue
  [ -a $IMGMD5 ] || {
    wget -kc -nv $URLBASE/$IMGMD5 -O $IMGMD5
    sed -i 's/  .\+$/'"  $IMG"'/' "$IMGMD5"
  }
done

md5sum --check --quiet snf_image_*.md5sum
```

**Comment by skalkoto** [comment]
I've checked it and 0.19rc2 is not missing. The image you are looking for is `http://cdn.synnefo.org/snf_image_helper_image-0.19rc2.tar.xz`. I completely forgot about that. It's the Debian version crap. The software's version is 0.19rc2 which is larger than 0.19rc1 but smaller than 0.19.  In Debian context the `~` is used to define a smaller version. `2~a` is smaller that `2` but larger that `1`, but `2rc1` is greater than `2`. So, you need to put the `~` thing for `apt` to check the version correctly.

**Comment by kasimon** [comment]
Understood. Debian package version ordering can be tricky sometimes, but stripping the tilde from the version number works, I can now mirror all images. Great!
